services:
  - type: web
    name: stentgraft-sizing
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_VERSION
        value: 18
